import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Playfair, Poppins } from "next/font/google";
import "./globals.css";

import {Providers} from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700" , "900" , "500" , "600" , "100" ], 
  variable: "--font-poppins",
});


const playFair = Playfair({
  subsets : ["latin"],
  weight : ["300" , "400" , "500" , "600" , "700" , "800" , "900"],
    variable : "--font-playfair"
})




const openSans = Open_Sans({
  subsets : ["latin"],
  weight : ["300", "400" , "600" , "500" , "700", "800"],
  variable : "--sansFont"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${poppins.variable} ${openSans.variable} ${playFair.variable} `}
      > 

<Providers>
        {children}

        </Providers>
      </body>
    </html>
  );
}

// antialiased
